// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpc/order.proto

package taxi_order_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RouteGuideClient is the client API for RouteGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteGuideClient interface {
	RateDriver(ctx context.Context, in *DriverRatingReq, opts ...grpc.CallOption) (*Response, error)
	RateUser(ctx context.Context, in *UserRatingReq, opts ...grpc.CallOption) (*Response, error)
	CreateOrder(ctx context.Context, in *OrderReq, opts ...grpc.CallOption) (*OrderResponse, error)
	FindDriverForOrder(ctx context.Context, in *FindDriverReq, opts ...grpc.CallOption) (*FindDriverResponse, error)
	FindOrders(ctx context.Context, in *FindOrdersReq, opts ...grpc.CallOption) (*Orders, error)
}

type routeGuideClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteGuideClient(cc grpc.ClientConnInterface) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) RateDriver(ctx context.Context, in *DriverRatingReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.RouteGuide/RateDriver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) RateUser(ctx context.Context, in *UserRatingReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.RouteGuide/RateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) CreateOrder(ctx context.Context, in *OrderReq, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/grpc.RouteGuide/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) FindDriverForOrder(ctx context.Context, in *FindDriverReq, opts ...grpc.CallOption) (*FindDriverResponse, error) {
	out := new(FindDriverResponse)
	err := c.cc.Invoke(ctx, "/grpc.RouteGuide/FindDriverForOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) FindOrders(ctx context.Context, in *FindOrdersReq, opts ...grpc.CallOption) (*Orders, error) {
	out := new(Orders)
	err := c.cc.Invoke(ctx, "/grpc.RouteGuide/FindOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteGuideServer is the server API for RouteGuide service.
// All implementations must embed UnimplementedRouteGuideServer
// for forward compatibility
type RouteGuideServer interface {
	RateDriver(context.Context, *DriverRatingReq) (*Response, error)
	RateUser(context.Context, *UserRatingReq) (*Response, error)
	CreateOrder(context.Context, *OrderReq) (*OrderResponse, error)
	FindDriverForOrder(context.Context, *FindDriverReq) (*FindDriverResponse, error)
	FindOrders(context.Context, *FindOrdersReq) (*Orders, error)
	mustEmbedUnimplementedRouteGuideServer()
}

// UnimplementedRouteGuideServer must be embedded to have forward compatible implementations.
type UnimplementedRouteGuideServer struct {
}

func (UnimplementedRouteGuideServer) RateDriver(context.Context, *DriverRatingReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateDriver not implemented")
}
func (UnimplementedRouteGuideServer) RateUser(context.Context, *UserRatingReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateUser not implemented")
}
func (UnimplementedRouteGuideServer) CreateOrder(context.Context, *OrderReq) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedRouteGuideServer) FindDriverForOrder(context.Context, *FindDriverReq) (*FindDriverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDriverForOrder not implemented")
}
func (UnimplementedRouteGuideServer) FindOrders(context.Context, *FindOrdersReq) (*Orders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOrders not implemented")
}
func (UnimplementedRouteGuideServer) mustEmbedUnimplementedRouteGuideServer() {}

// UnsafeRouteGuideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteGuideServer will
// result in compilation errors.
type UnsafeRouteGuideServer interface {
	mustEmbedUnimplementedRouteGuideServer()
}

func RegisterRouteGuideServer(s grpc.ServiceRegistrar, srv RouteGuideServer) {
	s.RegisterService(&RouteGuide_ServiceDesc, srv)
}

func _RouteGuide_RateDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverRatingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).RateDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.RouteGuide/RateDriver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).RateDriver(ctx, req.(*DriverRatingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_RateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRatingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).RateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.RouteGuide/RateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).RateUser(ctx, req.(*UserRatingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.RouteGuide/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).CreateOrder(ctx, req.(*OrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_FindDriverForOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).FindDriverForOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.RouteGuide/FindDriverForOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).FindDriverForOrder(ctx, req.(*FindDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_FindOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).FindOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.RouteGuide/FindOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).FindOrders(ctx, req.(*FindOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RouteGuide_ServiceDesc is the grpc.ServiceDesc for RouteGuide service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteGuide_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RateDriver",
			Handler:    _RouteGuide_RateDriver_Handler,
		},
		{
			MethodName: "RateUser",
			Handler:    _RouteGuide_RateUser_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _RouteGuide_CreateOrder_Handler,
		},
		{
			MethodName: "FindDriverForOrder",
			Handler:    _RouteGuide_FindDriverForOrder_Handler,
		},
		{
			MethodName: "FindOrders",
			Handler:    _RouteGuide_FindOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/order.proto",
}
